global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    environment: research

scrape_configs:

  - job_name: gateway-service
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s

  - job_name: order-service
    static_configs:
      - targets: ['order-service:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s

  - job_name: notification-service
    static_configs:
      - targets: ['notification-service:8082']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s

  - job_name: analytics-service
    static_configs:
      - targets: ['analytics-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
